### ISSUE TITLE
Unknown state for pull request: 'behind'

### ISSUE THREAD

**Issue by zapteryx** [reitermarkus/automerge#1493] opened 2022-07-20 01:43 UTC
Hi! I've been using this action for a while and it's been pretty helpful with my protected branches.
It appears that the action doesn't seem to recognize the state 'behind' which means that the pull request is not up to date with the target branch. Here's an example of the error: https://github.com/ZPTXDev/Quaver/actions/runs/2701520700
Is this intended?

**Comment by reitermarkus** [comment] 2022-07-26 16:32
Hi @zapteryx, no this is not intended.

Do you have the “Always suggest updating pull request branches” enabled on this repo? I assume this state was added when this feature was introduced.

Should be easy to just add this to https://github.com/reitermarkus/automerge/blob/787b521aaca9ba47b0d8132320958c06da33ad29/src/automerge-action.ts#L155-L160.

**Comment by zapteryx** [comment] 2022-07-26 19:20
I have this branch protection rule: 
![image](https://user-images.githubusercontent.com/9896328/181093700-47885afc-0551-4480-942b-394a0cb06198.png)
I don't have that feature enabled though: 
![image](https://user-images.githubusercontent.com/9896328/181093798-14343fc6-feaa-445a-9a0e-2e6628a795b3.png)

**Comment by reitermarkus** [comment] 2022-07-29 10:42
Thanks @zapteryx, I was able to reproduce the state. After adding it to the list it is working now:

https://github.com/reitermarkus/automerge/runs/7577285036?check_suite_focus=true#step:4:405

**Comment by reitermarkus** [comment] 2022-07-29 10:46
Fixed in v2.1.1.

**Closed by reitermarkus** 2022-07-29 10:46 UTC
